name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt install libsdl2-dev libsdl2-image-dev
        cargo build --verbose

  formatter:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt -- --check

  linter:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Check clippy
      run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: [formatter, linter]

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        sudo apt install libsdl2-dev libsdl2-image-dev
        RUST_MIN_STACK=8388608 cargo test --verbose
  
